// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.2
// source: user.proto

package user

import (
	context "context"
	common "github.com/huyshop/header/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// user
	SignIn(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignInResponse, error)
	SignOut(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Users, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	IsExistUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.IsExist, error)
	SendResetPasswordOtp(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.TTL, error)
	ResetPassword(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// customer
	SignInAfterVerifyOtp(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignInResponse, error)
	SignInCustomer(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignInResponse, error)
	VerifyEmail(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	SendVerifyOtp(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.TTL, error)
	CreateCustomer(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error)
	// userPoint
	GetUserPoint(ctx context.Context, in *UserPointRequest, opts ...grpc.CallOption) (*UserPoint, error)
	ListUserPoint(ctx context.Context, in *UserPointRequest, opts ...grpc.CallOption) (*UserPoints, error)
	// point_exchange
	ListPointExchange(ctx context.Context, in *PointExchangeRequest, opts ...grpc.CallOption) (*PointExchanges, error)
	GetPointExchange(ctx context.Context, in *PointExchange, opts ...grpc.CallOption) (*PointExchange, error)
	CreatePointExchange(ctx context.Context, in *PointExchange, opts ...grpc.CallOption) (*PointExchange, error)
	// store
	ListStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*Stores, error)
	GetStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*Store, error)
	CreateStore(ctx context.Context, in *Store, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateStore(ctx context.Context, in *Store, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteStore(ctx context.Context, in *Store, opts ...grpc.CallOption) (*common.Empty, error)
	CountStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*common.Count, error)
	// partner
	ListPartner(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*Partners, error)
	GetPartner(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*Partner, error)
	CreatePartner(ctx context.Context, in *Partner, opts ...grpc.CallOption) (*common.Empty, error)
	UpdatePartner(ctx context.Context, in *Partner, opts ...grpc.CallOption) (*common.Empty, error)
	DeletePartner(ctx context.Context, in *Partner, opts ...grpc.CallOption) (*common.Empty, error)
	// plans
	ListPlans(ctx context.Context, in *PlansRequest, opts ...grpc.CallOption) (*Plans, error)
	GetPlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*Plan, error)
	CreatePlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*common.Empty, error)
	UpdatePlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*common.Empty, error)
	DeletePlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*common.Empty, error)
	// order_plan
	ListOrderPlan(ctx context.Context, in *OrderPlanRequest, opts ...grpc.CallOption) (*OrderPlans, error)
	GetOrderPlan(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*OrderPlan, error)
	CreateOrderPlan(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*OrderPlan, error)
	UpdateOrderPlan(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*common.Empty, error)
	CreateOrderPlanVNpay(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*common.Empty, error)
	ListUserAddress(ctx context.Context, in *UserAddressRequest, opts ...grpc.CallOption) (*UserAddresses, error)
	GetUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error)
	CreateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*common.Empty, error)
	// report
	GetReportUser(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportUsers, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignIn(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignOut(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/user.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsExistUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.IsExist, error) {
	out := new(common.IsExist)
	err := c.cc.Invoke(ctx, "/user.UserService/IsExistUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendResetPasswordOtp(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.TTL, error) {
	out := new(common.TTL)
	err := c.cc.Invoke(ctx, "/user.UserService/SendResetPasswordOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignInAfterVerifyOtp(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/SignInAfterVerifyOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignInCustomer(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/SignInCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyEmail(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendVerifyOtp(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.TTL, error) {
	out := new(common.TTL)
	err := c.cc.Invoke(ctx, "/user.UserService/SendVerifyOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateCustomer(ctx context.Context, in *User, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserPoint(ctx context.Context, in *UserPointRequest, opts ...grpc.CallOption) (*UserPoint, error) {
	out := new(UserPoint)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUserPoint(ctx context.Context, in *UserPointRequest, opts ...grpc.CallOption) (*UserPoints, error) {
	out := new(UserPoints)
	err := c.cc.Invoke(ctx, "/user.UserService/ListUserPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListPointExchange(ctx context.Context, in *PointExchangeRequest, opts ...grpc.CallOption) (*PointExchanges, error) {
	out := new(PointExchanges)
	err := c.cc.Invoke(ctx, "/user.UserService/ListPointExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPointExchange(ctx context.Context, in *PointExchange, opts ...grpc.CallOption) (*PointExchange, error) {
	out := new(PointExchange)
	err := c.cc.Invoke(ctx, "/user.UserService/GetPointExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatePointExchange(ctx context.Context, in *PointExchange, opts ...grpc.CallOption) (*PointExchange, error) {
	out := new(PointExchange)
	err := c.cc.Invoke(ctx, "/user.UserService/CreatePointExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*Stores, error) {
	out := new(Stores)
	err := c.cc.Invoke(ctx, "/user.UserService/ListStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/user.UserService/GetStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateStore(ctx context.Context, in *Store, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateStore(ctx context.Context, in *Store, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteStore(ctx context.Context, in *Store, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CountStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*common.Count, error) {
	out := new(common.Count)
	err := c.cc.Invoke(ctx, "/user.UserService/CountStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListPartner(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*Partners, error) {
	out := new(Partners)
	err := c.cc.Invoke(ctx, "/user.UserService/ListPartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPartner(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*Partner, error) {
	out := new(Partner)
	err := c.cc.Invoke(ctx, "/user.UserService/GetPartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatePartner(ctx context.Context, in *Partner, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreatePartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePartner(ctx context.Context, in *Partner, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdatePartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletePartner(ctx context.Context, in *Partner, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/DeletePartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListPlans(ctx context.Context, in *PlansRequest, opts ...grpc.CallOption) (*Plans, error) {
	out := new(Plans)
	err := c.cc.Invoke(ctx, "/user.UserService/ListPlans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*Plan, error) {
	out := new(Plan)
	err := c.cc.Invoke(ctx, "/user.UserService/GetPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatePlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreatePlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdatePlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletePlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/DeletePlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListOrderPlan(ctx context.Context, in *OrderPlanRequest, opts ...grpc.CallOption) (*OrderPlans, error) {
	out := new(OrderPlans)
	err := c.cc.Invoke(ctx, "/user.UserService/ListOrderPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetOrderPlan(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*OrderPlan, error) {
	out := new(OrderPlan)
	err := c.cc.Invoke(ctx, "/user.UserService/GetOrderPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateOrderPlan(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*OrderPlan, error) {
	out := new(OrderPlan)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateOrderPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateOrderPlan(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateOrderPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateOrderPlanVNpay(ctx context.Context, in *OrderPlan, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateOrderPlanVNpay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUserAddress(ctx context.Context, in *UserAddressRequest, opts ...grpc.CallOption) (*UserAddresses, error) {
	out := new(UserAddresses)
	err := c.cc.Invoke(ctx, "/user.UserService/ListUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error) {
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetReportUser(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportUsers, error) {
	out := new(ReportUsers)
	err := c.cc.Invoke(ctx, "/user.UserService/GetReportUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations should embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// user
	SignIn(context.Context, *User) (*SignInResponse, error)
	SignOut(context.Context, *User) (*common.Empty, error)
	GetUser(context.Context, *UserRequest) (*User, error)
	ListUsers(context.Context, *UserRequest) (*Users, error)
	CreateUser(context.Context, *User) (*common.Empty, error)
	UpdateUser(context.Context, *User) (*common.Empty, error)
	DeleteUser(context.Context, *User) (*common.Empty, error)
	IsExistUser(context.Context, *User) (*common.IsExist, error)
	SendResetPasswordOtp(context.Context, *User) (*common.TTL, error)
	ResetPassword(context.Context, *User) (*common.Empty, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*common.Empty, error)
	// customer
	SignInAfterVerifyOtp(context.Context, *User) (*SignInResponse, error)
	SignInCustomer(context.Context, *User) (*SignInResponse, error)
	VerifyEmail(context.Context, *User) (*common.Empty, error)
	SendVerifyOtp(context.Context, *User) (*common.TTL, error)
	CreateCustomer(context.Context, *User) (*common.Empty, error)
	// userPoint
	GetUserPoint(context.Context, *UserPointRequest) (*UserPoint, error)
	ListUserPoint(context.Context, *UserPointRequest) (*UserPoints, error)
	// point_exchange
	ListPointExchange(context.Context, *PointExchangeRequest) (*PointExchanges, error)
	GetPointExchange(context.Context, *PointExchange) (*PointExchange, error)
	CreatePointExchange(context.Context, *PointExchange) (*PointExchange, error)
	// store
	ListStore(context.Context, *StoreRequest) (*Stores, error)
	GetStore(context.Context, *StoreRequest) (*Store, error)
	CreateStore(context.Context, *Store) (*common.Empty, error)
	UpdateStore(context.Context, *Store) (*common.Empty, error)
	DeleteStore(context.Context, *Store) (*common.Empty, error)
	CountStore(context.Context, *StoreRequest) (*common.Count, error)
	// partner
	ListPartner(context.Context, *PartnerRequest) (*Partners, error)
	GetPartner(context.Context, *PartnerRequest) (*Partner, error)
	CreatePartner(context.Context, *Partner) (*common.Empty, error)
	UpdatePartner(context.Context, *Partner) (*common.Empty, error)
	DeletePartner(context.Context, *Partner) (*common.Empty, error)
	// plans
	ListPlans(context.Context, *PlansRequest) (*Plans, error)
	GetPlan(context.Context, *Plan) (*Plan, error)
	CreatePlan(context.Context, *Plan) (*common.Empty, error)
	UpdatePlan(context.Context, *Plan) (*common.Empty, error)
	DeletePlan(context.Context, *Plan) (*common.Empty, error)
	// order_plan
	ListOrderPlan(context.Context, *OrderPlanRequest) (*OrderPlans, error)
	GetOrderPlan(context.Context, *OrderPlan) (*OrderPlan, error)
	CreateOrderPlan(context.Context, *OrderPlan) (*OrderPlan, error)
	UpdateOrderPlan(context.Context, *OrderPlan) (*common.Empty, error)
	CreateOrderPlanVNpay(context.Context, *OrderPlan) (*common.Empty, error)
	ListUserAddress(context.Context, *UserAddressRequest) (*UserAddresses, error)
	GetUserAddress(context.Context, *UserAddress) (*UserAddress, error)
	CreateUserAddress(context.Context, *UserAddress) (*common.Empty, error)
	UpdateUserAddress(context.Context, *UserAddress) (*common.Empty, error)
	DeleteUserAddress(context.Context, *UserAddress) (*common.Empty, error)
	// report
	GetReportUser(context.Context, *ReportRequest) (*ReportUsers, error)
}

// UnimplementedUserServiceServer should be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) SignIn(context.Context, *User) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedUserServiceServer) SignOut(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) ListUsers(context.Context, *UserRequest) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserServiceServer) CreateUser(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServiceServer) IsExistUser(context.Context, *User) (*common.IsExist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsExistUser not implemented")
}
func (UnimplementedUserServiceServer) SendResetPasswordOtp(context.Context, *User) (*common.TTL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResetPasswordOtp not implemented")
}
func (UnimplementedUserServiceServer) ResetPassword(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedUserServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserServiceServer) SignInAfterVerifyOtp(context.Context, *User) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInAfterVerifyOtp not implemented")
}
func (UnimplementedUserServiceServer) SignInCustomer(context.Context, *User) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInCustomer not implemented")
}
func (UnimplementedUserServiceServer) VerifyEmail(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedUserServiceServer) SendVerifyOtp(context.Context, *User) (*common.TTL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVerifyOtp not implemented")
}
func (UnimplementedUserServiceServer) CreateCustomer(context.Context, *User) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedUserServiceServer) GetUserPoint(context.Context, *UserPointRequest) (*UserPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPoint not implemented")
}
func (UnimplementedUserServiceServer) ListUserPoint(context.Context, *UserPointRequest) (*UserPoints, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserPoint not implemented")
}
func (UnimplementedUserServiceServer) ListPointExchange(context.Context, *PointExchangeRequest) (*PointExchanges, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPointExchange not implemented")
}
func (UnimplementedUserServiceServer) GetPointExchange(context.Context, *PointExchange) (*PointExchange, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPointExchange not implemented")
}
func (UnimplementedUserServiceServer) CreatePointExchange(context.Context, *PointExchange) (*PointExchange, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePointExchange not implemented")
}
func (UnimplementedUserServiceServer) ListStore(context.Context, *StoreRequest) (*Stores, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStore not implemented")
}
func (UnimplementedUserServiceServer) GetStore(context.Context, *StoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedUserServiceServer) CreateStore(context.Context, *Store) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedUserServiceServer) UpdateStore(context.Context, *Store) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStore not implemented")
}
func (UnimplementedUserServiceServer) DeleteStore(context.Context, *Store) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedUserServiceServer) CountStore(context.Context, *StoreRequest) (*common.Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountStore not implemented")
}
func (UnimplementedUserServiceServer) ListPartner(context.Context, *PartnerRequest) (*Partners, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPartner not implemented")
}
func (UnimplementedUserServiceServer) GetPartner(context.Context, *PartnerRequest) (*Partner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartner not implemented")
}
func (UnimplementedUserServiceServer) CreatePartner(context.Context, *Partner) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartner not implemented")
}
func (UnimplementedUserServiceServer) UpdatePartner(context.Context, *Partner) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePartner not implemented")
}
func (UnimplementedUserServiceServer) DeletePartner(context.Context, *Partner) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePartner not implemented")
}
func (UnimplementedUserServiceServer) ListPlans(context.Context, *PlansRequest) (*Plans, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedUserServiceServer) GetPlan(context.Context, *Plan) (*Plan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedUserServiceServer) CreatePlan(context.Context, *Plan) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedUserServiceServer) UpdatePlan(context.Context, *Plan) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlan not implemented")
}
func (UnimplementedUserServiceServer) DeletePlan(context.Context, *Plan) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlan not implemented")
}
func (UnimplementedUserServiceServer) ListOrderPlan(context.Context, *OrderPlanRequest) (*OrderPlans, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrderPlan not implemented")
}
func (UnimplementedUserServiceServer) GetOrderPlan(context.Context, *OrderPlan) (*OrderPlan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderPlan not implemented")
}
func (UnimplementedUserServiceServer) CreateOrderPlan(context.Context, *OrderPlan) (*OrderPlan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderPlan not implemented")
}
func (UnimplementedUserServiceServer) UpdateOrderPlan(context.Context, *OrderPlan) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderPlan not implemented")
}
func (UnimplementedUserServiceServer) CreateOrderPlanVNpay(context.Context, *OrderPlan) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderPlanVNpay not implemented")
}
func (UnimplementedUserServiceServer) ListUserAddress(context.Context, *UserAddressRequest) (*UserAddresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserAddress not implemented")
}
func (UnimplementedUserServiceServer) GetUserAddress(context.Context, *UserAddress) (*UserAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAddress not implemented")
}
func (UnimplementedUserServiceServer) CreateUserAddress(context.Context, *UserAddress) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAddress not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserAddress(context.Context, *UserAddress) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAddress not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserAddress(context.Context, *UserAddress) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAddress not implemented")
}
func (UnimplementedUserServiceServer) GetReportUser(context.Context, *ReportRequest) (*ReportUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportUser not implemented")
}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignIn(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignOut(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsExistUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsExistUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/IsExistUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsExistUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendResetPasswordOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendResetPasswordOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SendResetPasswordOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendResetPasswordOtp(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignInAfterVerifyOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignInAfterVerifyOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SignInAfterVerifyOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignInAfterVerifyOtp(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignInCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignInCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SignInCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignInCustomer(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyEmail(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendVerifyOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendVerifyOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SendVerifyOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendVerifyOtp(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateCustomer(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserPoint(ctx, req.(*UserPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUserPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUserPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListUserPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUserPoint(ctx, req.(*UserPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListPointExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListPointExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListPointExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListPointExchange(ctx, req.(*PointExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPointExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointExchange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPointExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetPointExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPointExchange(ctx, req.(*PointExchange))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatePointExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointExchange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatePointExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreatePointExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatePointExchange(ctx, req.(*PointExchange))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListStore(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetStore(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Store)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateStore(ctx, req.(*Store))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Store)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateStore(ctx, req.(*Store))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Store)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteStore(ctx, req.(*Store))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CountStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CountStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CountStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CountStore(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListPartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListPartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListPartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListPartner(ctx, req.(*PartnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetPartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPartner(ctx, req.(*PartnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatePartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Partner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatePartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreatePartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatePartner(ctx, req.(*Partner))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Partner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdatePartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePartner(ctx, req.(*Partner))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletePartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Partner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletePartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeletePartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletePartner(ctx, req.(*Partner))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListPlans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListPlans(ctx, req.(*PlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPlan(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreatePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatePlan(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdatePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePlan(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeletePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletePlan(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListOrderPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListOrderPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListOrderPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListOrderPlan(ctx, req.(*OrderPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetOrderPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetOrderPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetOrderPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetOrderPlan(ctx, req.(*OrderPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateOrderPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateOrderPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateOrderPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateOrderPlan(ctx, req.(*OrderPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateOrderPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateOrderPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateOrderPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateOrderPlan(ctx, req.(*OrderPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateOrderPlanVNpay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateOrderPlanVNpay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateOrderPlanVNpay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateOrderPlanVNpay(ctx, req.(*OrderPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ListUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUserAddress(ctx, req.(*UserAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetReportUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetReportUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetReportUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetReportUser(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _UserService_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _UserService_SignOut_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "IsExistUser",
			Handler:    _UserService_IsExistUser_Handler,
		},
		{
			MethodName: "SendResetPasswordOtp",
			Handler:    _UserService_SendResetPasswordOtp_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
		{
			MethodName: "SignInAfterVerifyOtp",
			Handler:    _UserService_SignInAfterVerifyOtp_Handler,
		},
		{
			MethodName: "SignInCustomer",
			Handler:    _UserService_SignInCustomer_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _UserService_VerifyEmail_Handler,
		},
		{
			MethodName: "SendVerifyOtp",
			Handler:    _UserService_SendVerifyOtp_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _UserService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetUserPoint",
			Handler:    _UserService_GetUserPoint_Handler,
		},
		{
			MethodName: "ListUserPoint",
			Handler:    _UserService_ListUserPoint_Handler,
		},
		{
			MethodName: "ListPointExchange",
			Handler:    _UserService_ListPointExchange_Handler,
		},
		{
			MethodName: "GetPointExchange",
			Handler:    _UserService_GetPointExchange_Handler,
		},
		{
			MethodName: "CreatePointExchange",
			Handler:    _UserService_CreatePointExchange_Handler,
		},
		{
			MethodName: "ListStore",
			Handler:    _UserService_ListStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _UserService_GetStore_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _UserService_CreateStore_Handler,
		},
		{
			MethodName: "UpdateStore",
			Handler:    _UserService_UpdateStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _UserService_DeleteStore_Handler,
		},
		{
			MethodName: "CountStore",
			Handler:    _UserService_CountStore_Handler,
		},
		{
			MethodName: "ListPartner",
			Handler:    _UserService_ListPartner_Handler,
		},
		{
			MethodName: "GetPartner",
			Handler:    _UserService_GetPartner_Handler,
		},
		{
			MethodName: "CreatePartner",
			Handler:    _UserService_CreatePartner_Handler,
		},
		{
			MethodName: "UpdatePartner",
			Handler:    _UserService_UpdatePartner_Handler,
		},
		{
			MethodName: "DeletePartner",
			Handler:    _UserService_DeletePartner_Handler,
		},
		{
			MethodName: "ListPlans",
			Handler:    _UserService_ListPlans_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _UserService_GetPlan_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _UserService_CreatePlan_Handler,
		},
		{
			MethodName: "UpdatePlan",
			Handler:    _UserService_UpdatePlan_Handler,
		},
		{
			MethodName: "DeletePlan",
			Handler:    _UserService_DeletePlan_Handler,
		},
		{
			MethodName: "ListOrderPlan",
			Handler:    _UserService_ListOrderPlan_Handler,
		},
		{
			MethodName: "GetOrderPlan",
			Handler:    _UserService_GetOrderPlan_Handler,
		},
		{
			MethodName: "CreateOrderPlan",
			Handler:    _UserService_CreateOrderPlan_Handler,
		},
		{
			MethodName: "UpdateOrderPlan",
			Handler:    _UserService_UpdateOrderPlan_Handler,
		},
		{
			MethodName: "CreateOrderPlanVNpay",
			Handler:    _UserService_CreateOrderPlanVNpay_Handler,
		},
		{
			MethodName: "ListUserAddress",
			Handler:    _UserService_ListUserAddress_Handler,
		},
		{
			MethodName: "GetUserAddress",
			Handler:    _UserService_GetUserAddress_Handler,
		},
		{
			MethodName: "CreateUserAddress",
			Handler:    _UserService_CreateUserAddress_Handler,
		},
		{
			MethodName: "UpdateUserAddress",
			Handler:    _UserService_UpdateUserAddress_Handler,
		},
		{
			MethodName: "DeleteUserAddress",
			Handler:    _UserService_DeleteUserAddress_Handler,
		},
		{
			MethodName: "GetReportUser",
			Handler:    _UserService_GetReportUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
