// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.2
// source: product.proto

package product

import (
	context "context"
	common "github.com/huyshop/header/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	// category
	ListCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*Categories, error)
	GetCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*Category, error)
	CreateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*common.Empty, error)
	// product typereviews
	ListProductType(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*ProductTypes, error)
	GetProductType(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*ProductType, error)
	GetProductTypeBySlug(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*ProductType, error)
	CreateProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateStateProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error)
	CountProductType(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*common.Count, error)
	UpdateProductTypeAdmin(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error)
	// product
	ListProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Products, error)
	GetProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Product, error)
	// banner
	ListBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*Banners, error)
	GetBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*Banner, error)
	CreateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*common.Empty, error)
	// cart
	ListCart(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error)
	AddToCart(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error)
	DeleteCart(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error)
	DeleteCartItem(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error)
	// order
	GetOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*Order, error)
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	ListOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*Orders, error)
	CreateOrderVNpay(ctx context.Context, in *Order, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateStateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*common.Empty, error)
	// // order ship
	// rpc CreateOrderShip (Order) returns (common.Empty);
	UpdateOrderShipStatus(ctx context.Context, in *OrderShip, opts ...grpc.CallOption) (*common.Empty, error)
	// reviews
	ListReviews(ctx context.Context, in *ReviewsRequest, opts ...grpc.CallOption) (*Reviewss, error)
	GetReviews(ctx context.Context, in *ReviewsRequest, opts ...grpc.CallOption) (*Reviews, error)
	CreateReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error)
	ReplyReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error)
	CountReviews(ctx context.Context, in *ReviewsRequest, opts ...grpc.CallOption) (*common.Count, error)
	// report
	GetReportOverview(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportOverview, error)
	GetReportRevenue(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportRevenue, error)
	GetReportStoreRevenue(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportStoreRevenue, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) ListCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*Categories, error) {
	out := new(Categories)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProductType(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*ProductTypes, error) {
	out := new(ProductTypes)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductType(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*ProductType, error) {
	out := new(ProductType)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductTypeBySlug(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*ProductType, error) {
	out := new(ProductType)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductTypeBySlug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateStateProductType(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateStateProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CountProductType(ctx context.Context, in *ProductTypeRequest, opts ...grpc.CallOption) (*common.Count, error) {
	out := new(common.Count)
	err := c.cc.Invoke(ctx, "/product.ProductService/CountProductType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProductTypeAdmin(ctx context.Context, in *ProductType, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProductTypeAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Products, error) {
	out := new(Products)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*Banners, error) {
	out := new(Banners)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*Banner, error) {
	out := new(Banner)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListCart(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddToCart(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteCart(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteCartItem(ctx context.Context, in *Cart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*Orders, error) {
	out := new(Orders)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateOrderVNpay(ctx context.Context, in *Order, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateOrderVNpay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateStateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateStateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateOrderShipStatus(ctx context.Context, in *OrderShip, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateOrderShipStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListReviews(ctx context.Context, in *ReviewsRequest, opts ...grpc.CallOption) (*Reviewss, error) {
	out := new(Reviewss)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetReviews(ctx context.Context, in *ReviewsRequest, opts ...grpc.CallOption) (*Reviews, error) {
	out := new(Reviews)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ReplyReviews(ctx context.Context, in *Reviews, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/ReplyReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CountReviews(ctx context.Context, in *ReviewsRequest, opts ...grpc.CallOption) (*common.Count, error) {
	out := new(common.Count)
	err := c.cc.Invoke(ctx, "/product.ProductService/CountReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetReportOverview(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportOverview, error) {
	out := new(ReportOverview)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetReportOverview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetReportRevenue(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportRevenue, error) {
	out := new(ReportRevenue)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetReportRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetReportStoreRevenue(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportStoreRevenue, error) {
	out := new(ReportStoreRevenue)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetReportStoreRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations should embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	// category
	ListCategory(context.Context, *CategoryRequest) (*Categories, error)
	GetCategory(context.Context, *CategoryRequest) (*Category, error)
	CreateCategory(context.Context, *Category) (*common.Empty, error)
	UpdateCategory(context.Context, *Category) (*common.Empty, error)
	DeleteCategory(context.Context, *Category) (*common.Empty, error)
	// product typereviews
	ListProductType(context.Context, *ProductTypeRequest) (*ProductTypes, error)
	GetProductType(context.Context, *ProductTypeRequest) (*ProductType, error)
	GetProductTypeBySlug(context.Context, *ProductTypeRequest) (*ProductType, error)
	CreateProductType(context.Context, *ProductType) (*common.Empty, error)
	UpdateProductType(context.Context, *ProductType) (*common.Empty, error)
	DeleteProductType(context.Context, *ProductType) (*common.Empty, error)
	UpdateStateProductType(context.Context, *ProductType) (*common.Empty, error)
	CountProductType(context.Context, *ProductTypeRequest) (*common.Count, error)
	UpdateProductTypeAdmin(context.Context, *ProductType) (*common.Empty, error)
	// product
	ListProduct(context.Context, *ProductRequest) (*Products, error)
	GetProduct(context.Context, *ProductRequest) (*Product, error)
	// banner
	ListBanner(context.Context, *BannerRequest) (*Banners, error)
	GetBanner(context.Context, *BannerRequest) (*Banner, error)
	CreateBanner(context.Context, *Banner) (*common.Empty, error)
	UpdateBanner(context.Context, *Banner) (*common.Empty, error)
	DeleteBanner(context.Context, *Banner) (*common.Empty, error)
	// cart
	ListCart(context.Context, *Cart) (*Cart, error)
	AddToCart(context.Context, *Cart) (*Cart, error)
	DeleteCart(context.Context, *Cart) (*Cart, error)
	DeleteCartItem(context.Context, *Cart) (*Cart, error)
	// order
	GetOrder(context.Context, *OrderRequest) (*Order, error)
	CreateOrder(context.Context, *Order) (*Order, error)
	ListOrder(context.Context, *OrderRequest) (*Orders, error)
	CreateOrderVNpay(context.Context, *Order) (*common.Empty, error)
	UpdateStateOrder(context.Context, *Order) (*common.Empty, error)
	// // order ship
	// rpc CreateOrderShip (Order) returns (common.Empty);
	UpdateOrderShipStatus(context.Context, *OrderShip) (*common.Empty, error)
	// reviews
	ListReviews(context.Context, *ReviewsRequest) (*Reviewss, error)
	GetReviews(context.Context, *ReviewsRequest) (*Reviews, error)
	CreateReviews(context.Context, *Reviews) (*common.Empty, error)
	UpdateReviews(context.Context, *Reviews) (*common.Empty, error)
	DeleteReviews(context.Context, *Reviews) (*common.Empty, error)
	ReplyReviews(context.Context, *Reviews) (*common.Empty, error)
	CountReviews(context.Context, *ReviewsRequest) (*common.Count, error)
	// report
	GetReportOverview(context.Context, *ReportRequest) (*ReportOverview, error)
	GetReportRevenue(context.Context, *ReportRequest) (*ReportRevenue, error)
	GetReportStoreRevenue(context.Context, *ReportRequest) (*ReportStoreRevenue, error)
}

// UnimplementedProductServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) ListCategory(context.Context, *CategoryRequest) (*Categories, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategory not implemented")
}
func (UnimplementedProductServiceServer) GetCategory(context.Context, *CategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedProductServiceServer) CreateCategory(context.Context, *Category) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedProductServiceServer) UpdateCategory(context.Context, *Category) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedProductServiceServer) DeleteCategory(context.Context, *Category) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedProductServiceServer) ListProductType(context.Context, *ProductTypeRequest) (*ProductTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductType not implemented")
}
func (UnimplementedProductServiceServer) GetProductType(context.Context, *ProductTypeRequest) (*ProductType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductType not implemented")
}
func (UnimplementedProductServiceServer) GetProductTypeBySlug(context.Context, *ProductTypeRequest) (*ProductType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductTypeBySlug not implemented")
}
func (UnimplementedProductServiceServer) CreateProductType(context.Context, *ProductType) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductType not implemented")
}
func (UnimplementedProductServiceServer) UpdateProductType(context.Context, *ProductType) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductType not implemented")
}
func (UnimplementedProductServiceServer) DeleteProductType(context.Context, *ProductType) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductType not implemented")
}
func (UnimplementedProductServiceServer) UpdateStateProductType(context.Context, *ProductType) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStateProductType not implemented")
}
func (UnimplementedProductServiceServer) CountProductType(context.Context, *ProductTypeRequest) (*common.Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountProductType not implemented")
}
func (UnimplementedProductServiceServer) UpdateProductTypeAdmin(context.Context, *ProductType) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductTypeAdmin not implemented")
}
func (UnimplementedProductServiceServer) ListProduct(context.Context, *ProductRequest) (*Products, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProduct(context.Context, *ProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) ListBanner(context.Context, *BannerRequest) (*Banners, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBanner not implemented")
}
func (UnimplementedProductServiceServer) GetBanner(context.Context, *BannerRequest) (*Banner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBanner not implemented")
}
func (UnimplementedProductServiceServer) CreateBanner(context.Context, *Banner) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBanner not implemented")
}
func (UnimplementedProductServiceServer) UpdateBanner(context.Context, *Banner) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBanner not implemented")
}
func (UnimplementedProductServiceServer) DeleteBanner(context.Context, *Banner) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedProductServiceServer) ListCart(context.Context, *Cart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCart not implemented")
}
func (UnimplementedProductServiceServer) AddToCart(context.Context, *Cart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedProductServiceServer) DeleteCart(context.Context, *Cart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCart not implemented")
}
func (UnimplementedProductServiceServer) DeleteCartItem(context.Context, *Cart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCartItem not implemented")
}
func (UnimplementedProductServiceServer) GetOrder(context.Context, *OrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedProductServiceServer) CreateOrder(context.Context, *Order) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedProductServiceServer) ListOrder(context.Context, *OrderRequest) (*Orders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrder not implemented")
}
func (UnimplementedProductServiceServer) CreateOrderVNpay(context.Context, *Order) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderVNpay not implemented")
}
func (UnimplementedProductServiceServer) UpdateStateOrder(context.Context, *Order) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStateOrder not implemented")
}
func (UnimplementedProductServiceServer) UpdateOrderShipStatus(context.Context, *OrderShip) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderShipStatus not implemented")
}
func (UnimplementedProductServiceServer) ListReviews(context.Context, *ReviewsRequest) (*Reviewss, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReviews not implemented")
}
func (UnimplementedProductServiceServer) GetReviews(context.Context, *ReviewsRequest) (*Reviews, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviews not implemented")
}
func (UnimplementedProductServiceServer) CreateReviews(context.Context, *Reviews) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReviews not implemented")
}
func (UnimplementedProductServiceServer) UpdateReviews(context.Context, *Reviews) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReviews not implemented")
}
func (UnimplementedProductServiceServer) DeleteReviews(context.Context, *Reviews) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReviews not implemented")
}
func (UnimplementedProductServiceServer) ReplyReviews(context.Context, *Reviews) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyReviews not implemented")
}
func (UnimplementedProductServiceServer) CountReviews(context.Context, *ReviewsRequest) (*common.Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountReviews not implemented")
}
func (UnimplementedProductServiceServer) GetReportOverview(context.Context, *ReportRequest) (*ReportOverview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportOverview not implemented")
}
func (UnimplementedProductServiceServer) GetReportRevenue(context.Context, *ReportRequest) (*ReportRevenue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportRevenue not implemented")
}
func (UnimplementedProductServiceServer) GetReportStoreRevenue(context.Context, *ReportRequest) (*ReportStoreRevenue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportStoreRevenue not implemented")
}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_ListCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListCategory(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCategory(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProductType(ctx, req.(*ProductTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductType(ctx, req.(*ProductTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductTypeBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductTypeBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductTypeBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductTypeBySlug(ctx, req.(*ProductTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProductType(ctx, req.(*ProductType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProductType(ctx, req.(*ProductType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProductType(ctx, req.(*ProductType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateStateProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateStateProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateStateProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateStateProductType(ctx, req.(*ProductType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CountProductType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CountProductType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CountProductType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CountProductType(ctx, req.(*ProductTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProductTypeAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProductTypeAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProductTypeAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProductTypeAdmin(ctx, req.(*ProductType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Banner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateBanner(ctx, req.(*Banner))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Banner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateBanner(ctx, req.(*Banner))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Banner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteBanner(ctx, req.(*Banner))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListCart(ctx, req.(*Cart))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddToCart(ctx, req.(*Cart))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteCart(ctx, req.(*Cart))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteCartItem(ctx, req.(*Cart))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateOrderVNpay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateOrderVNpay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateOrderVNpay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateOrderVNpay(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateStateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateStateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateStateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateStateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateOrderShipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderShip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateOrderShipStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateOrderShipStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateOrderShipStatus(ctx, req.(*OrderShip))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListReviews(ctx, req.(*ReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetReviews(ctx, req.(*ReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reviews)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateReviews(ctx, req.(*Reviews))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reviews)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateReviews(ctx, req.(*Reviews))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reviews)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteReviews(ctx, req.(*Reviews))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ReplyReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reviews)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ReplyReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ReplyReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ReplyReviews(ctx, req.(*Reviews))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CountReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CountReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CountReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CountReviews(ctx, req.(*ReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetReportOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetReportOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetReportOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetReportOverview(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetReportRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetReportRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetReportRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetReportRevenue(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetReportStoreRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetReportStoreRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetReportStoreRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetReportStoreRevenue(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCategory",
			Handler:    _ProductService_ListCategory_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ProductService_GetCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _ProductService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ProductService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _ProductService_DeleteCategory_Handler,
		},
		{
			MethodName: "ListProductType",
			Handler:    _ProductService_ListProductType_Handler,
		},
		{
			MethodName: "GetProductType",
			Handler:    _ProductService_GetProductType_Handler,
		},
		{
			MethodName: "GetProductTypeBySlug",
			Handler:    _ProductService_GetProductTypeBySlug_Handler,
		},
		{
			MethodName: "CreateProductType",
			Handler:    _ProductService_CreateProductType_Handler,
		},
		{
			MethodName: "UpdateProductType",
			Handler:    _ProductService_UpdateProductType_Handler,
		},
		{
			MethodName: "DeleteProductType",
			Handler:    _ProductService_DeleteProductType_Handler,
		},
		{
			MethodName: "UpdateStateProductType",
			Handler:    _ProductService_UpdateStateProductType_Handler,
		},
		{
			MethodName: "CountProductType",
			Handler:    _ProductService_CountProductType_Handler,
		},
		{
			MethodName: "UpdateProductTypeAdmin",
			Handler:    _ProductService_UpdateProductTypeAdmin_Handler,
		},
		{
			MethodName: "ListProduct",
			Handler:    _ProductService_ListProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "ListBanner",
			Handler:    _ProductService_ListBanner_Handler,
		},
		{
			MethodName: "GetBanner",
			Handler:    _ProductService_GetBanner_Handler,
		},
		{
			MethodName: "CreateBanner",
			Handler:    _ProductService_CreateBanner_Handler,
		},
		{
			MethodName: "UpdateBanner",
			Handler:    _ProductService_UpdateBanner_Handler,
		},
		{
			MethodName: "DeleteBanner",
			Handler:    _ProductService_DeleteBanner_Handler,
		},
		{
			MethodName: "ListCart",
			Handler:    _ProductService_ListCart_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _ProductService_AddToCart_Handler,
		},
		{
			MethodName: "DeleteCart",
			Handler:    _ProductService_DeleteCart_Handler,
		},
		{
			MethodName: "DeleteCartItem",
			Handler:    _ProductService_DeleteCartItem_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _ProductService_GetOrder_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _ProductService_CreateOrder_Handler,
		},
		{
			MethodName: "ListOrder",
			Handler:    _ProductService_ListOrder_Handler,
		},
		{
			MethodName: "CreateOrderVNpay",
			Handler:    _ProductService_CreateOrderVNpay_Handler,
		},
		{
			MethodName: "UpdateStateOrder",
			Handler:    _ProductService_UpdateStateOrder_Handler,
		},
		{
			MethodName: "UpdateOrderShipStatus",
			Handler:    _ProductService_UpdateOrderShipStatus_Handler,
		},
		{
			MethodName: "ListReviews",
			Handler:    _ProductService_ListReviews_Handler,
		},
		{
			MethodName: "GetReviews",
			Handler:    _ProductService_GetReviews_Handler,
		},
		{
			MethodName: "CreateReviews",
			Handler:    _ProductService_CreateReviews_Handler,
		},
		{
			MethodName: "UpdateReviews",
			Handler:    _ProductService_UpdateReviews_Handler,
		},
		{
			MethodName: "DeleteReviews",
			Handler:    _ProductService_DeleteReviews_Handler,
		},
		{
			MethodName: "ReplyReviews",
			Handler:    _ProductService_ReplyReviews_Handler,
		},
		{
			MethodName: "CountReviews",
			Handler:    _ProductService_CountReviews_Handler,
		},
		{
			MethodName: "GetReportOverview",
			Handler:    _ProductService_GetReportOverview_Handler,
		},
		{
			MethodName: "GetReportRevenue",
			Handler:    _ProductService_GetReportRevenue_Handler,
		},
		{
			MethodName: "GetReportStoreRevenue",
			Handler:    _ProductService_GetReportStoreRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
