// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.2
// source: voucher.proto

package voucher

import (
	context "context"
	common "github.com/huyshop/header/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoucherServiceClient is the client API for VoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherServiceClient interface {
	// Voucher
	CreateVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*common.Empty, error)
	GetVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*Voucher, error)
	DeleteVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*common.Empty, error)
	ListVouchers(ctx context.Context, in *VoucherRequest, opts ...grpc.CallOption) (*Vouchers, error)
	ListVouchersCustomer(ctx context.Context, in *VoucherRequest, opts ...grpc.CallOption) (*Vouchers, error)
	// Code
	CreateCode(ctx context.Context, in *Code, opts ...grpc.CallOption) (*common.Empty, error)
	UseCode(ctx context.Context, in *Code, opts ...grpc.CallOption) (*Code, error)
	ListCodes(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*Codes, error)
	VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// UserVoucher
	ListUserVouchers(ctx context.Context, in *UserVoucherRequest, opts ...grpc.CallOption) (*UserVouchers, error)
	GetUserVoucher(ctx context.Context, in *UserVoucher, opts ...grpc.CallOption) (*UserVoucher, error)
	UpdateUserVoucher(ctx context.Context, in *UserVoucher, opts ...grpc.CallOption) (*UserVoucher, error)
	CreateUserVoucher(ctx context.Context, in *UserVoucher, opts ...grpc.CallOption) (*UserVoucher, error)
}

type voucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceClient(cc grpc.ClientConnInterface) VoucherServiceClient {
	return &voucherServiceClient{cc}
}

func (c *voucherServiceClient) CreateVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/CreateVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) UpdateVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/UpdateVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) GetVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*Voucher, error) {
	out := new(Voucher)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/GetVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) DeleteVoucher(ctx context.Context, in *Voucher, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/DeleteVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) ListVouchers(ctx context.Context, in *VoucherRequest, opts ...grpc.CallOption) (*Vouchers, error) {
	out := new(Vouchers)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/ListVouchers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) ListVouchersCustomer(ctx context.Context, in *VoucherRequest, opts ...grpc.CallOption) (*Vouchers, error) {
	out := new(Vouchers)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/ListVouchersCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) CreateCode(ctx context.Context, in *Code, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/CreateCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) UseCode(ctx context.Context, in *Code, opts ...grpc.CallOption) (*Code, error) {
	out := new(Code)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/UseCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) ListCodes(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*Codes, error) {
	out := new(Codes)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/ListCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/VerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) ListUserVouchers(ctx context.Context, in *UserVoucherRequest, opts ...grpc.CallOption) (*UserVouchers, error) {
	out := new(UserVouchers)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/ListUserVouchers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) GetUserVoucher(ctx context.Context, in *UserVoucher, opts ...grpc.CallOption) (*UserVoucher, error) {
	out := new(UserVoucher)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/GetUserVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) UpdateUserVoucher(ctx context.Context, in *UserVoucher, opts ...grpc.CallOption) (*UserVoucher, error) {
	out := new(UserVoucher)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/UpdateUserVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) CreateUserVoucher(ctx context.Context, in *UserVoucher, opts ...grpc.CallOption) (*UserVoucher, error) {
	out := new(UserVoucher)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/CreateUserVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServiceServer is the server API for VoucherService service.
// All implementations should embed UnimplementedVoucherServiceServer
// for forward compatibility
type VoucherServiceServer interface {
	// Voucher
	CreateVoucher(context.Context, *Voucher) (*common.Empty, error)
	UpdateVoucher(context.Context, *Voucher) (*common.Empty, error)
	GetVoucher(context.Context, *Voucher) (*Voucher, error)
	DeleteVoucher(context.Context, *Voucher) (*common.Empty, error)
	ListVouchers(context.Context, *VoucherRequest) (*Vouchers, error)
	ListVouchersCustomer(context.Context, *VoucherRequest) (*Vouchers, error)
	// Code
	CreateCode(context.Context, *Code) (*common.Empty, error)
	UseCode(context.Context, *Code) (*Code, error)
	ListCodes(context.Context, *CodeRequest) (*Codes, error)
	VerifyCode(context.Context, *VerifyCodeRequest) (*common.Empty, error)
	// UserVoucher
	ListUserVouchers(context.Context, *UserVoucherRequest) (*UserVouchers, error)
	GetUserVoucher(context.Context, *UserVoucher) (*UserVoucher, error)
	UpdateUserVoucher(context.Context, *UserVoucher) (*UserVoucher, error)
	CreateUserVoucher(context.Context, *UserVoucher) (*UserVoucher, error)
}

// UnimplementedVoucherServiceServer should be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceServer struct {
}

func (UnimplementedVoucherServiceServer) CreateVoucher(context.Context, *Voucher) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) UpdateVoucher(context.Context, *Voucher) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) GetVoucher(context.Context, *Voucher) (*Voucher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) DeleteVoucher(context.Context, *Voucher) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) ListVouchers(context.Context, *VoucherRequest) (*Vouchers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVouchers not implemented")
}
func (UnimplementedVoucherServiceServer) ListVouchersCustomer(context.Context, *VoucherRequest) (*Vouchers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVouchersCustomer not implemented")
}
func (UnimplementedVoucherServiceServer) CreateCode(context.Context, *Code) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCode not implemented")
}
func (UnimplementedVoucherServiceServer) UseCode(context.Context, *Code) (*Code, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseCode not implemented")
}
func (UnimplementedVoucherServiceServer) ListCodes(context.Context, *CodeRequest) (*Codes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCodes not implemented")
}
func (UnimplementedVoucherServiceServer) VerifyCode(context.Context, *VerifyCodeRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCode not implemented")
}
func (UnimplementedVoucherServiceServer) ListUserVouchers(context.Context, *UserVoucherRequest) (*UserVouchers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserVouchers not implemented")
}
func (UnimplementedVoucherServiceServer) GetUserVoucher(context.Context, *UserVoucher) (*UserVoucher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) UpdateUserVoucher(context.Context, *UserVoucher) (*UserVoucher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserVoucher not implemented")
}
func (UnimplementedVoucherServiceServer) CreateUserVoucher(context.Context, *UserVoucher) (*UserVoucher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserVoucher not implemented")
}

// UnsafeVoucherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServiceServer will
// result in compilation errors.
type UnsafeVoucherServiceServer interface {
	mustEmbedUnimplementedVoucherServiceServer()
}

func RegisterVoucherServiceServer(s grpc.ServiceRegistrar, srv VoucherServiceServer) {
	s.RegisterService(&VoucherService_ServiceDesc, srv)
}

func _VoucherService_CreateVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Voucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).CreateVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/CreateVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).CreateVoucher(ctx, req.(*Voucher))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_UpdateVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Voucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).UpdateVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/UpdateVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).UpdateVoucher(ctx, req.(*Voucher))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_GetVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Voucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).GetVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/GetVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).GetVoucher(ctx, req.(*Voucher))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_DeleteVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Voucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).DeleteVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/DeleteVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).DeleteVoucher(ctx, req.(*Voucher))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_ListVouchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ListVouchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/ListVouchers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ListVouchers(ctx, req.(*VoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_ListVouchersCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ListVouchersCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/ListVouchersCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ListVouchersCustomer(ctx, req.(*VoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_CreateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Code)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).CreateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/CreateCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).CreateCode(ctx, req.(*Code))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_UseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Code)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).UseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/UseCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).UseCode(ctx, req.(*Code))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_ListCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ListCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/ListCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ListCodes(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_VerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).VerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/VerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).VerifyCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_ListUserVouchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ListUserVouchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/ListUserVouchers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ListUserVouchers(ctx, req.(*UserVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_GetUserVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVoucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).GetUserVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/GetUserVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).GetUserVoucher(ctx, req.(*UserVoucher))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_UpdateUserVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVoucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).UpdateUserVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/UpdateUserVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).UpdateUserVoucher(ctx, req.(*UserVoucher))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_CreateUserVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVoucher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).CreateUserVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/CreateUserVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).CreateUserVoucher(ctx, req.(*UserVoucher))
	}
	return interceptor(ctx, in, info, handler)
}

// VoucherService_ServiceDesc is the grpc.ServiceDesc for VoucherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoucherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voucher.VoucherService",
	HandlerType: (*VoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVoucher",
			Handler:    _VoucherService_CreateVoucher_Handler,
		},
		{
			MethodName: "UpdateVoucher",
			Handler:    _VoucherService_UpdateVoucher_Handler,
		},
		{
			MethodName: "GetVoucher",
			Handler:    _VoucherService_GetVoucher_Handler,
		},
		{
			MethodName: "DeleteVoucher",
			Handler:    _VoucherService_DeleteVoucher_Handler,
		},
		{
			MethodName: "ListVouchers",
			Handler:    _VoucherService_ListVouchers_Handler,
		},
		{
			MethodName: "ListVouchersCustomer",
			Handler:    _VoucherService_ListVouchersCustomer_Handler,
		},
		{
			MethodName: "CreateCode",
			Handler:    _VoucherService_CreateCode_Handler,
		},
		{
			MethodName: "UseCode",
			Handler:    _VoucherService_UseCode_Handler,
		},
		{
			MethodName: "ListCodes",
			Handler:    _VoucherService_ListCodes_Handler,
		},
		{
			MethodName: "VerifyCode",
			Handler:    _VoucherService_VerifyCode_Handler,
		},
		{
			MethodName: "ListUserVouchers",
			Handler:    _VoucherService_ListUserVouchers_Handler,
		},
		{
			MethodName: "GetUserVoucher",
			Handler:    _VoucherService_GetUserVoucher_Handler,
		},
		{
			MethodName: "UpdateUserVoucher",
			Handler:    _VoucherService_UpdateUserVoucher_Handler,
		},
		{
			MethodName: "CreateUserVoucher",
			Handler:    _VoucherService_CreateUserVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voucher.proto",
}
